CREATE DATABASE SKYFLICK;
USE SKYFLICK;
CREATE TABLE PASSENGER_INFO(
    NAME VARCHAR(100),
    GENDER VARCHAR(10),
    DOB DATE,
    NATIONALITY VARCHAR(15),
    ID_NAME VARCHAR(100),
    ID_NUMBER VARCHAR(50),
    EMAIL VARCHAR(100),
    CONTACT_NUMBER VARCHAR(15),
    ALTERNATE_CONTACT_NUMBER VARCHAR(15),
    ADDRESS VARCHAR(255)
);
CREATE TABLE TRIP_CLASS (
    TRIP_TYPE VARCHAR(10),
    CLASS_TYPE VARCHAR(20)
);
CREATE TABLE SEAT(
    NUMBER_OF_PASSENGER INT,
    PASSENGER_TYPE VARCHAR(20),
    SEAT_PREFERENCE VARCHAR(10)
);
CREATE TABLE ADD_SERVICES(
    EXTRA_BAGGAGE BOOLEAN,
    MEAL_PREFERENCE VARCHAR(50),
    SPECIAL_ASSISTANCE BOOLEAN
);
CREATE TABLE PAYMENT_INFO(
    PAYMENT_METHOD VARCHAR(20)
);