USE DATABASE SKYFLICK;
CREATE TABLE SIGNUP (
    USER_NAME VARCHAR(100) PRIMARY KEY,
    Email VARCHAR(100) UNIQUE,
    Password VARCHAR(255)
);
CREATE TABLE SIGNIN(
    USER_NAME VARCHAR(100) PRIMARY KEY,
    Password VARCHAR(255)
);
